services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: devfreela
    ports:
      - "5432:5432"
    volumes: 
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
